spring:
  jpa:
    database: postgresql
    show-sql: true 
    generate-ddl: false
    hibernate: 
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        type: trace 
  datasource:
    url: ${HEROKU_POSTGRESQL_AMBER_URL}
#    username: root
#    password: adminadmin
    driverClassName: org.postgresql.Driver
    connectionTimeout: 20000
    maxPoolSize: 10
    maxActive: 10
    maxIdle: 10
    initialSize: 5
    idleTimeout: 300000
    minIdle: 10
    poolName: heropost-connection-pool
    removeAbandoned: true