spring:
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate: 
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        type: trace    
datasource:
  datalinks:
    860141: HEROKU_POSTGRESQL_AMBER_URL
    36177: HEROKU_POSTGRESQL_AQUA_URL
#    0: HEROKU_POSTGRESQL_BLACK_URL
#    0: HEROKU_POSTGRESQL_BLUE_URL
#    0: HEROKU_POSTGRESQL_BRONZE_URL
#    0: HEROKU_POSTGRESQL_BROWN_URL
#    0: HEROKU_POSTGRESQL_CHARCOAL_URL
#    0: HEROKU_POSTGRESQL_COBALT_URL
#    0: HEROKU_POSTGRESQL_COPPER_URL
#    0: HEROKU_POSTGRESQL_CRIMSON_URL
#    0: HEROKU_POSTGRESQL_CYAN_URL
#    0: HEROKU_POSTGRESQL_GOLD_URL
#    0: HEROKU_POSTGRESQL_GRAY_URL
#    0: HEROKU_POSTGRESQL_GREEN_URL
#    0: HEROKU_POSTGRESQL_IVORY_URL
#    0: HEROKU_POSTGRESQL_JADE_URL
#    0: HEROKU_POSTGRESQL_MAROON_URL
#    0: HEROKU_POSTGRESQL_MAUVE_URL
#    0: HEROKU_POSTGRESQL_NAVY_URL
#    0: HEROKU_POSTGRESQL_OLIVE_URL
#    0: HEROKU_POSTGRESQL_ONYX_URL
#    0: HEROKU_POSTGRESQL_ORANGE_URL
#    0: HEROKU_POSTGRESQL_PINK_URL
#    0: HEROKU_POSTGRESQL_PUCE_URL
#    0: HEROKU_POSTGRESQL_PURPLE_URL
#    0: HEROKU_POSTGRESQL_RED_URL
#    0: HEROKU_POSTGRESQL_ROSE_URL
#    0: HEROKU_POSTGRESQL_SILVER_URL
#    0: HEROKU_POSTGRESQL_TEAL_URL
#    0: HEROKU_POSTGRESQL_TEAL_URL
#    0: HEROKU_POSTGRESQL_YELLOW_URL
