spring:
  jpa:
    show-sql: false 
    generate-ddl: true
    hibernate:      
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        type: trace        
  datasource:
    driverClassName: org.postgresql.Driver
    connectionTimeout: 20000
    maxPoolSize: 10
    maxActive: 10
    maxIdle: 10
    initialSize: 5
    idleTimeout: 300000
    minIdle: 10
    poolName: app-connection-pool
    removeAbandoned: true
datasource:
  datalinks:
    T01: DATABASE_URL
    T02: HEROKU_POSTGRESQL_AMBER_URL
    T03: HEROKU_POSTGRESQL_AQUA_URL
    T04: HEROKU_POSTGRESQL_BLACK_URL
    T05: HEROKU_POSTGRESQL_BLUE_URL
    T06: HEROKU_POSTGRESQL_BRONZE_URL
    T07: HEROKU_POSTGRESQL_BROWN_URL
    T08: HEROKU_POSTGRESQL_CHARCOAL_URL
    T09: HEROKU_POSTGRESQL_COBALT_URL
    T10: HEROKU_POSTGRESQL_COPPER_URL
    T11: HEROKU_POSTGRESQL_CRIMSON_URL
    T12: HEROKU_POSTGRESQL_CYAN_URL
    T13: HEROKU_POSTGRESQL_GOLD_URL
    T14: HEROKU_POSTGRESQL_GRAY_URL
    T15: HEROKU_POSTGRESQL_GREEN_URL
    T16: HEROKU_POSTGRESQL_IVORY_URL
    T17: HEROKU_POSTGRESQL_JADE_URL
    T18: HEROKU_POSTGRESQL_MAROON_URL
    T19: HEROKU_POSTGRESQL_MAUVE_URL
    T20: HEROKU_POSTGRESQL_NAVY_URL
    T21: HEROKU_POSTGRESQL_OLIVE_URL
    T22: HEROKU_POSTGRESQL_ONYX_URL
    T23: HEROKU_POSTGRESQL_ORANGE_URL
    T24: HEROKU_POSTGRESQL_PINK_URL
    T25: HEROKU_POSTGRESQL_PUCE_URL
    T26: HEROKU_POSTGRESQL_PURPLE_URL
    T27: HEROKU_POSTGRESQL_RED_URL
    T28: HEROKU_POSTGRESQL_ROSE_URL
    T29: HEROKU_POSTGRESQL_SILVER_URL
    T30: HEROKU_POSTGRESQL_TEAL_URL
    T31: HEROKU_POSTGRESQL_WHITE_URL
    T32: HEROKU_POSTGRESQL_YELLOW_URL